#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-assembly-plugin
Version  : 3.1.0
Release  : 1
URL      : https://github.com/apache/maven-assembly-plugin/archive/maven-assembly-plugin-3.1.0.tar.gz
Source0  : https://github.com/apache/maven-assembly-plugin/archive/maven-assembly-plugin-3.1.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/3.1.0/maven-assembly-plugin-3.1.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/3.1.0/maven-assembly-plugin-3.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
MASSEMBLY-111

%prep

%build

%install

%files
%defattr(-,root,root,-)
